### ISSUE TITLE
torch-sparse error

### ISSUE THREAD

**Issue by ugrkilc** [qwerfdsaplking/Graph-Trans#3]
I am getting errors on TORCH-SPARSE installation.
Do you have any suggestions about this?

**Comment by ugrkilc** [comment]
Traceback (most recent call last):
  File "C:\Users\UGUR\Desktop\WORKSPACE\Graph-Trans-main\run.py", line 8, in <module>        
    from gt_dataset import *
  File "C:\Users\UGUR\Desktop\WORKSPACE\Graph-Trans-main\gt_dataset.py", line 10, in <module>
    from data.pyg_datasets.pyg_dataset import GraphormerPYGDataset, Graphtrans_Sampling_Dataset,Graphtrans_Sampling_Dataset_v2
  File "C:\Users\UGUR\Desktop\WORKSPACE\Graph-Trans-main\data\pyg_datasets\__init__.py", line 4, in <module>
    from .pyg_dataset_lookup_table import PYGDatasetLookupTable
  File "C:\Users\UGUR\Desktop\WORKSPACE\Graph-Trans-main\data\pyg_datasets\pyg_dataset_lookup_table.py", line 7, in <module>
    from .pyg_dataset import GraphormerPYGDataset
  File "C:\Users\UGUR\Desktop\WORKSPACE\Graph-Trans-main\data\pyg_datasets\pyg_dataset.py", line 6, in <module>
    from torch_sparse import SparseTensor
ModuleNotFoundError: No module named 'torch_sparse'



**I can't install TORCH-SPARSE
I tried so many different ways**
